"""World ID / IDKit integration helpers for wallet-bound verification."""

from __future__ import annotations

import os
import json
import secrets as random_secrets
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Mapping
from urllib import error as urllib_error
from urllib import parse as urllib_parse
from urllib import request as urllib_request
from urllib.parse import urlparse

from ._vendor import ensure_ipfs_datasets_py_path

ensure_ipfs_datasets_py_path()

from ipfs_datasets_py.utils.secrets import resolve_secret  # noqa: E402

try:  # pragma: no cover - import failure is exercised by dependency health checks.
    from Crypto.Hash import keccak  # type: ignore[import-untyped]  # noqa: E402
except ImportError as exc:  # pragma: no cover
    keccak = None  # type: ignore[assignment]
    _KECCAK_IMPORT_ERROR = exc
else:
    _KECCAK_IMPORT_ERROR = None

try:  # pragma: no cover - import failure is exercised by dependency health checks.
    from coincurve import PrivateKey  # type: ignore[import-untyped]  # noqa: E402
except ImportError as exc:  # pragma: no cover
    PrivateKey = None  # type: ignore[assignment]
    _SIGNING_IMPORT_ERROR = exc
else:
    _SIGNING_IMPORT_ERROR = None


DEFAULT_WORLD_ID_ACTION = "wallet-attach-world-id-v1"
DEFAULT_WORLD_ID_CREDENTIAL_POLICY = "proof_of_human"
DEFAULT_WORLD_ID_VERIFY_BASE_URL = "https://developer.world.org"
DEFAULT_WORLD_ID_SIGNATURE_TTL_SECONDS = 300
DEFAULT_WORLD_ID_HTTP_TIMEOUT_SECONDS = 15.0
SUPPORTED_WORLD_ID_ENVIRONMENTS = {"staging", "production"}

_PUBLIC_SECRET_ENV_NAMES = {
    "ABBY_RUNTIME_WORLD_ID_NULLIFIER_HMAC_KEY",
    "ABBY_RUNTIME_WORLD_ID_RP_SIGNING_KEY",
    "VITE_WORLD_ID_NULLIFIER_HMAC_KEY",
    "VITE_WORLD_ID_RP_SIGNING_KEY",
}


class WorldIdConfigError(ValueError):
    """Raised when World ID backend configuration is invalid."""


class WorldIdSignatureError(ValueError):
    """Raised when RP signature generation inputs are invalid."""


class WorldIdVerificationError(RuntimeError):
    """Raised when Developer Portal proof verification fails operationally."""


class WorldIdPayloadError(ValueError):
    """Raised when an IDKit proof payload is malformed or unsupported."""


WorldIdRequestJson = Callable[[str, str, Mapping[str, Any], Mapping[str, str], float], Mapping[str, Any]]


@dataclass(frozen=True)
class WorldIdRpSignature:
    """World ID RP signature payload generated by the backend."""

    signature: str
    nonce: str
    created_at: int
    expires_at: int
    action: str | None = None

    def to_protocol_dict(self) -> dict[str, object]:
        """Return the protocol field names used by World ID signing docs."""

        return {
            "sig": self.signature,
            "nonce": self.nonce,
            "created_at": self.created_at,
            "expires_at": self.expires_at,
        }

    def to_rp_context(self, rp_id: str) -> dict[str, object]:
        """Return an IDKit-ready RP context with the relying-party ID."""

        return {
            "rp_id": rp_id,
            **self.to_protocol_dict(),
        }


@dataclass(frozen=True)
class WorldIdVerificationResult:
    """Normalized response from World Developer Portal verification."""

    success: bool
    action: str = ""
    nullifier: str = ""
    created_at: str = ""
    environment: str = ""
    session_id: str = ""
    message: str = ""
    results: tuple[Mapping[str, Any], ...] = ()
    raw_response: Mapping[str, Any] = field(default_factory=dict, repr=False)

    @property
    def successful_results(self) -> tuple[Mapping[str, Any], ...]:
        return tuple(result for result in self.results if bool(result.get("success")))

    def public_dict(self) -> dict[str, object]:
        return {
            "success": self.success,
            "action": self.action,
            "nullifier": self.nullifier,
            "created_at": self.created_at,
            "environment": self.environment,
            "session_id": self.session_id,
            "message": self.message,
            "results": [redact_world_id_payload(dict(result)) for result in self.results],
        }


@dataclass(frozen=True)
class WorldIdCredentialResponse:
    """Normalized metadata for one IDKit credential response."""

    identifier: str
    proof_type: str
    signal_hash: str = field(default="", repr=False)
    nullifier: str = field(default="", repr=False)
    session_nullifier: str = field(default="", repr=False)
    session_action: str = field(default="", repr=False)
    issuer_schema_id: int | None = None
    expires_at_min: int | None = None

    @property
    def credential_identifier(self) -> str:
        return self.identifier

    @property
    def nullifier_value(self) -> str:
        return self.session_nullifier or self.nullifier

    def public_dict(self) -> dict[str, object]:
        return {
            "identifier": self.identifier,
            "proof_type": self.proof_type,
            "has_signal_hash": bool(self.signal_hash),
            "has_nullifier": bool(self.nullifier_value),
            "has_session_action": bool(self.session_action),
            "issuer_schema_id": self.issuer_schema_id,
            "expires_at_min": self.expires_at_min,
        }


@dataclass(frozen=True)
class WorldIdIdkitResult:
    """Normalized IDKit result metadata across v3 legacy, v4 uniqueness, and v4 session proofs."""

    protocol_version: str
    nonce: str
    environment: str
    proof_type: str
    responses: tuple[WorldIdCredentialResponse, ...]
    action: str = ""
    action_description: str = ""
    session_id: str = ""
    user_presence_completed: bool | None = None
    identity_attested: bool | None = None
    integrity_bundle_present: bool = False
    raw_response: Mapping[str, Any] = field(default_factory=dict, repr=False)

    @property
    def credential_identifiers(self) -> tuple[str, ...]:
        return tuple(response.identifier for response in self.responses)

    @property
    def signal_hashes(self) -> tuple[str, ...]:
        return tuple(response.signal_hash for response in self.responses if response.signal_hash)

    @property
    def nullifiers(self) -> tuple[str, ...]:
        return tuple(response.nullifier_value for response in self.responses if response.nullifier_value)

    @property
    def session_actions(self) -> tuple[str, ...]:
        return tuple(response.session_action for response in self.responses if response.session_action)

    @property
    def verification_timestamps(self) -> tuple[int, ...]:
        return tuple(
            response.expires_at_min for response in self.responses if response.expires_at_min is not None
        )

    @property
    def expires_at_min_values(self) -> tuple[int, ...]:
        return self.verification_timestamps

    def public_dict(self) -> dict[str, object]:
        return {
            "protocol_version": self.protocol_version,
            "nonce": self.nonce,
            "environment": self.environment,
            "proof_type": self.proof_type,
            "action": self.action,
            "action_description": self.action_description,
            "session_id": self.session_id,
            "user_presence_completed": self.user_presence_completed,
            "identity_attested": self.identity_attested,
            "integrity_bundle_present": self.integrity_bundle_present,
            "credential_identifiers": list(self.credential_identifiers),
            "nullifier_count": len(self.nullifiers),
            "signal_hash_count": len(self.signal_hashes),
            "verification_timestamps": list(self.verification_timestamps),
            "responses": [response.public_dict() for response in self.responses],
        }


@dataclass(frozen=True)
class WorldIdSecretConfig:
    """Backend-only secret configuration without exposing values in repr output."""

    value: str = field(default="", repr=False)
    secret_ref: str = ""

    @property
    def configured(self) -> bool:
        return bool(self.value or self.secret_ref)

    def public_dict(self) -> dict[str, bool | str]:
        return {
            "configured": self.configured,
            "source": "secret_ref" if self.secret_ref else ("direct" if self.value else ""),
        }


@dataclass(frozen=True)
class WorldIdConfig:
    """Validated backend configuration for World ID wallet binding."""

    enabled: bool
    environment: str = "staging"
    app_id: str = ""
    rp_id: str = ""
    allowed_actions: tuple[str, ...] = (DEFAULT_WORLD_ID_ACTION,)
    default_action: str = DEFAULT_WORLD_ID_ACTION
    credential_policy: str = DEFAULT_WORLD_ID_CREDENTIAL_POLICY
    allow_legacy_proofs: bool = True
    require_user_presence: bool = False
    rp_signature_ttl_seconds: int = DEFAULT_WORLD_ID_SIGNATURE_TTL_SECONDS
    verify_base_url: str = DEFAULT_WORLD_ID_VERIFY_BASE_URL
    http_timeout_seconds: float = DEFAULT_WORLD_ID_HTTP_TIMEOUT_SECONDS
    rp_signing_key: WorldIdSecretConfig = field(default_factory=WorldIdSecretConfig, repr=False)
    nullifier_hmac_key: WorldIdSecretConfig = field(default_factory=WorldIdSecretConfig, repr=False)

    @property
    def public_actions(self) -> list[str]:
        return list(self.allowed_actions)

    def public_dict(self) -> dict[str, object]:
        """Return browser-safe configuration without backend secrets."""

        return {
            "enabled": self.enabled,
            "environment": self.environment,
            "app_id": self.app_id,
            "rp_id": self.rp_id,
            "allowed_actions": list(self.allowed_actions),
            "default_action": self.default_action,
            "credential_policy": self.credential_policy,
            "allow_legacy_proofs": self.allow_legacy_proofs,
            "require_user_presence": self.require_user_presence,
            "rp_signature_ttl_seconds": self.rp_signature_ttl_seconds,
            "verify_base_url": self.verify_base_url,
            "http_timeout_seconds": self.http_timeout_seconds,
        }


def load_world_id_config(env: Mapping[str, str] | None = None) -> WorldIdConfig:
    """Load and validate World ID wallet-binding configuration."""

    _reject_public_secret_leaks(env)
    enabled = _bool_env(env, "WORLD_ID_ENABLED", default=False)
    environment = _str_env(env, "WORLD_ID_ENVIRONMENT", "staging").lower()
    if environment not in SUPPORTED_WORLD_ID_ENVIRONMENTS:
        raise WorldIdConfigError("WORLD_ID_ENVIRONMENT must be staging or production")

    default_action = _str_env(env, "WORLD_ID_DEFAULT_ACTION", DEFAULT_WORLD_ID_ACTION)
    allowed_actions = _actions_from_env(env, default_action)
    if default_action not in allowed_actions:
        raise WorldIdConfigError("WORLD_ID_DEFAULT_ACTION must be included in WORLD_ID_ALLOWED_ACTIONS")

    config = WorldIdConfig(
        enabled=enabled,
        environment=environment,
        app_id=_str_env(env, "WORLD_ID_APP_ID", ""),
        rp_id=_str_env(env, "WORLD_ID_RP_ID", ""),
        allowed_actions=tuple(allowed_actions),
        default_action=default_action,
        credential_policy=_str_env(env, "WORLD_ID_CREDENTIAL_POLICY", DEFAULT_WORLD_ID_CREDENTIAL_POLICY),
        allow_legacy_proofs=_bool_env(env, "WORLD_ID_ALLOW_LEGACY_PROOFS", default=True),
        require_user_presence=_bool_env(env, "WORLD_ID_REQUIRE_USER_PRESENCE", default=False),
        rp_signature_ttl_seconds=_positive_int_env(
            env,
            "WORLD_ID_RP_SIGNATURE_TTL_SECONDS",
            DEFAULT_WORLD_ID_SIGNATURE_TTL_SECONDS,
        ),
        verify_base_url=_url_env(env, "WORLD_ID_VERIFY_BASE_URL", DEFAULT_WORLD_ID_VERIFY_BASE_URL),
        http_timeout_seconds=_positive_float_env(
            env,
            "WORLD_ID_HTTP_TIMEOUT_SECONDS",
            DEFAULT_WORLD_ID_HTTP_TIMEOUT_SECONDS,
        ),
        rp_signing_key=WorldIdSecretConfig(
            value=_secret_env(env, "WORLD_ID_RP_SIGNING_KEY"),
            secret_ref=_str_env(env, "WORLD_ID_RP_SIGNING_KEY_SECRET_REF", ""),
        ),
        nullifier_hmac_key=WorldIdSecretConfig(
            value=_secret_env(env, "WORLD_ID_NULLIFIER_HMAC_KEY"),
            secret_ref=_str_env(env, "WORLD_ID_NULLIFIER_HMAC_KEY_SECRET_REF", ""),
        ),
    )
    if enabled:
        _validate_enabled_config(config)
    return config


def world_id_keccak256(data: bytes) -> bytes:
    """Return Ethereum Keccak-256, not NIST SHA3-256."""

    _require_keccak_dependency()
    digest = keccak.new(digest_bits=256)
    digest.update(data)
    return digest.digest()


def hash_to_field(input_bytes: bytes | str) -> bytes:
    """Hash bytes to the World ID field element representation."""

    data = input_bytes.encode("utf-8") if isinstance(input_bytes, str) else bytes(input_bytes)
    value = int.from_bytes(world_id_keccak256(data), "big") >> 8
    return value.to_bytes(32, "big")


def hash_to_field_hex(input_bytes: bytes | str) -> str:
    return "0x" + hash_to_field(input_bytes).hex()


def compute_rp_signature_message(
    nonce_bytes32: bytes | str,
    created_at: int,
    expires_at: int,
    action: str | None = None,
) -> bytes:
    """Build the exact bytes World ID requires before EIP-191 signing."""

    nonce = _parse_bytes32(nonce_bytes32, "nonce")
    created = _uint64(created_at, "created_at")
    expires = _uint64(expires_at, "expires_at")
    if expires <= created:
        raise WorldIdSignatureError("expires_at must be greater than created_at")
    message = b"\x01" + nonce + created.to_bytes(8, "big") + expires.to_bytes(8, "big")
    if action is not None:
        cleaned_action = str(action).strip()
        if not cleaned_action:
            raise WorldIdSignatureError("action must not be empty when provided")
        message += hash_to_field(cleaned_action)
    return message


def eip191_digest(message: bytes) -> bytes:
    """Apply the Ethereum Signed Message prefix and Keccak digest."""

    prefix = b"\x19Ethereum Signed Message:\n" + str(len(message)).encode("ascii")
    return world_id_keccak256(prefix + message)


def sign_world_id_request(
    signing_key_hex: str,
    *,
    action: str | None = None,
    ttl_seconds: int = DEFAULT_WORLD_ID_SIGNATURE_TTL_SECONDS,
    random_bytes: bytes | None = None,
    created_at: int | None = None,
) -> WorldIdRpSignature:
    """Generate a World ID RP signature from a backend signing key."""

    _require_signing_dependencies()
    key_bytes = _parse_private_key(signing_key_hex)
    ttl = int(ttl_seconds)
    if ttl <= 0:
        raise WorldIdSignatureError("ttl_seconds must be positive")
    created = int(time.time()) if created_at is None else _uint64(created_at, "created_at")
    expires = created + ttl
    if expires > (2**64 - 1):
        raise WorldIdSignatureError("expires_at exceeds uint64")
    entropy = random_secrets.token_bytes(32) if random_bytes is None else bytes(random_bytes)
    if len(entropy) != 32:
        raise WorldIdSignatureError("random_bytes must be exactly 32 bytes")
    nonce = hash_to_field(entropy)
    message = compute_rp_signature_message(nonce, created, expires, action)
    digest = eip191_digest(message)
    raw_signature = PrivateKey(key_bytes).sign_recoverable(digest, hasher=None)
    signature_bytes = raw_signature[:64] + bytes([int(raw_signature[64]) + 27])
    return WorldIdRpSignature(
        signature="0x" + signature_bytes.hex(),
        nonce="0x" + nonce.hex(),
        created_at=created,
        expires_at=expires,
        action=str(action).strip() if action is not None else None,
    )


def sign_world_id_request_from_config(
    config: WorldIdConfig,
    *,
    action: str | None = None,
    random_bytes: bytes | None = None,
    created_at: int | None = None,
) -> WorldIdRpSignature:
    """Generate an RP signature using a validated World ID config."""

    if not config.enabled:
        raise WorldIdSignatureError("World ID is disabled")
    selected_action = str(action or config.default_action).strip()
    if selected_action not in config.allowed_actions:
        raise WorldIdSignatureError("World ID action is not allowed")
    if not config.rp_signing_key.value:
        raise WorldIdSignatureError("WORLD_ID_RP_SIGNING_KEY value is required to sign requests")
    return sign_world_id_request(
        config.rp_signing_key.value,
        action=selected_action,
        ttl_seconds=config.rp_signature_ttl_seconds,
        random_bytes=random_bytes,
        created_at=created_at,
    )


def normalize_idkit_response(payload: Mapping[str, Any]) -> WorldIdIdkitResult:
    """Parse the IDKit result shapes returned by World ID 3.0 and 4.0 clients."""

    if not isinstance(payload, Mapping):
        raise WorldIdPayloadError("IDKit response payload must be a JSON object")

    protocol_version = _required_string_field(payload, "protocol_version", "IDKit response")
    if protocol_version not in {"3.0", "4.0"}:
        raise WorldIdPayloadError("IDKit response protocol_version must be 3.0 or 4.0")
    nonce = _required_string_field(payload, "nonce", "IDKit response")
    environment = _required_string_field(payload, "environment", "IDKit response").lower()
    if environment not in SUPPORTED_WORLD_ID_ENVIRONMENTS:
        raise WorldIdPayloadError("IDKit response environment must be staging or production")
    raw_responses = _response_items(payload)
    action_description = _optional_string_field(payload, "action_description", "IDKit response")
    user_presence_completed = _optional_bool_field(payload, "user_presence_completed", "IDKit response")
    identity_attested = _optional_bool_field(payload, "identity_attested", "IDKit response")
    integrity_bundle_present = _integrity_bundle_present(payload)

    if protocol_version == "3.0":
        action = _required_string_field(payload, "action", "IDKit response")
        if _optional_string_field(payload, "session_id", "IDKit response"):
            raise WorldIdPayloadError("IDKit 3.0 responses must not include session_id")
        responses = tuple(_normalize_v3_response(response, index) for index, response in enumerate(raw_responses))
        return WorldIdIdkitResult(
            protocol_version=protocol_version,
            nonce=nonce,
            environment=environment,
            proof_type="legacy",
            action=action,
            action_description=action_description,
            responses=responses,
            user_presence_completed=user_presence_completed,
            identity_attested=identity_attested,
            integrity_bundle_present=integrity_bundle_present,
            raw_response=dict(payload),
        )

    session_id = _optional_string_field(payload, "session_id", "IDKit response")
    has_session_responses = any("session_nullifier" in response for response in raw_responses)
    if session_id or has_session_responses:
        if not session_id:
            raise WorldIdPayloadError("IDKit 4.0 session responses require session_id")
        responses = tuple(
            _normalize_v4_session_response(response, index) for index, response in enumerate(raw_responses)
        )
        return WorldIdIdkitResult(
            protocol_version=protocol_version,
            nonce=nonce,
            environment=environment,
            proof_type="session",
            action=_optional_string_field(payload, "action", "IDKit response"),
            action_description=action_description,
            session_id=session_id,
            responses=responses,
            user_presence_completed=user_presence_completed,
            identity_attested=identity_attested,
            integrity_bundle_present=integrity_bundle_present,
            raw_response=dict(payload),
        )

    action = _required_string_field(payload, "action", "IDKit response")
    responses = tuple(_normalize_v4_response(response, index) for index, response in enumerate(raw_responses))
    return WorldIdIdkitResult(
        protocol_version=protocol_version,
        nonce=nonce,
        environment=environment,
        proof_type="uniqueness",
        action=action,
        action_description=action_description,
        responses=responses,
        user_presence_completed=user_presence_completed,
        identity_attested=identity_attested,
        integrity_bundle_present=integrity_bundle_present,
        raw_response=dict(payload),
    )


def normalize_world_id_idkit_response(payload: Mapping[str, Any]) -> WorldIdIdkitResult:
    """Alias with explicit World ID naming for API callers."""

    return normalize_idkit_response(payload)


def verify_world_id_proof(
    rp_id: str,
    idkit_payload: Mapping[str, Any],
    *,
    verify_base_url: str = DEFAULT_WORLD_ID_VERIFY_BASE_URL,
    timeout_seconds: float = DEFAULT_WORLD_ID_HTTP_TIMEOUT_SECONDS,
    request_json: WorldIdRequestJson | None = None,
) -> WorldIdVerificationResult:
    """Verify an IDKit result with the World Developer Portal."""

    resolved_rp_id = str(rp_id or "").strip()
    if not resolved_rp_id:
        raise WorldIdVerificationError("rp_id is required")
    base_url = _validate_base_url(verify_base_url)
    timeout = float(timeout_seconds)
    if timeout <= 0:
        raise WorldIdVerificationError("timeout_seconds must be positive")
    url = f"{base_url}/api/v4/verify/{urllib_parse.quote(resolved_rp_id, safe='')}"
    requester = request_json or _default_world_id_request_json
    try:
        response = requester(
            "POST",
            url,
            idkit_payload,
            {"content-type": "application/json"},
            timeout,
        )
    except WorldIdVerificationError:
        raise
    except Exception as exc:
        raise WorldIdVerificationError(f"World ID verification request failed: {_safe_error_message(exc)}") from exc
    return normalize_world_id_verification_response(response, idkit_payload=idkit_payload)


def verify_world_id_proof_from_config(
    config: WorldIdConfig,
    idkit_payload: Mapping[str, Any],
    *,
    request_json: WorldIdRequestJson | None = None,
) -> WorldIdVerificationResult:
    """Verify an IDKit result using a validated World ID config."""

    if not config.enabled:
        raise WorldIdVerificationError("World ID is disabled")
    return verify_world_id_proof(
        config.rp_id,
        idkit_payload,
        verify_base_url=config.verify_base_url,
        timeout_seconds=config.http_timeout_seconds,
        request_json=request_json,
    )


def normalize_world_id_verification_response(
    response: Mapping[str, Any],
    *,
    idkit_payload: Mapping[str, Any] | None = None,
) -> WorldIdVerificationResult:
    """Normalize a Developer Portal verification response."""

    if not isinstance(response, Mapping):
        raise WorldIdVerificationError("World ID verification response must be a JSON object")
    raw_results = response.get("results")
    if raw_results is None:
        raw_results = []
    if not isinstance(raw_results, list):
        raise WorldIdVerificationError("World ID verification response results must be a list")
    results = tuple(result for result in raw_results if isinstance(result, Mapping))
    payload = idkit_payload or {}
    nullifier = str(response.get("nullifier") or "")
    if not nullifier:
        nullifier = next((str(result.get("nullifier") or "") for result in results if result.get("nullifier")), "")
    return WorldIdVerificationResult(
        success=bool(response.get("success")),
        action=str(response.get("action") or payload.get("action") or ""),
        nullifier=nullifier,
        created_at=str(response.get("created_at") or ""),
        environment=str(response.get("environment") or payload.get("environment") or ""),
        session_id=str(response.get("session_id") or ""),
        message=str(response.get("message") or ""),
        results=results,
        raw_response=dict(response),
    )


def redact_world_id_payload(value: Any) -> Any:
    """Redact IDKit proof-heavy values before logging or surfacing errors."""

    sensitive_keys = {
        "integrity_bundle",
        "jwt",
        "merkle_root",
        "nullifier",
        "proof",
        "rp_signature",
        "responses",
        "root",
        "raw_response",
        "developer_portal_response",
        "idkit_payload",
        "session_nullifier",
        "signal_hash",
        "signature",
    }
    if isinstance(value, Mapping):
        redacted: dict[str, Any] = {}
        for key, item in value.items():
            lowered = str(key).lower()
            if lowered in sensitive_keys or lowered.endswith("_key"):
                redacted[str(key)] = "[redacted]"
            else:
                redacted[str(key)] = redact_world_id_payload(item)
        return redacted
    if isinstance(value, list):
        return [redact_world_id_payload(item) for item in value]
    return value


def _normalize_v3_response(response: Mapping[str, Any], index: int) -> WorldIdCredentialResponse:
    context = f"IDKit response responses[{index}]"
    _required_string_field(response, "proof", context)
    _required_string_field(response, "merkle_root", context)
    return WorldIdCredentialResponse(
        identifier=_required_string_field(response, "identifier", context),
        proof_type="legacy",
        signal_hash=_required_string_field(response, "signal_hash", context),
        nullifier=_required_string_field(response, "nullifier", context),
    )


def _normalize_v4_response(response: Mapping[str, Any], index: int) -> WorldIdCredentialResponse:
    context = f"IDKit response responses[{index}]"
    if "session_nullifier" in response:
        raise WorldIdPayloadError(f"{context} must not include session_nullifier for uniqueness proofs")
    _proof_list(response, context)
    return WorldIdCredentialResponse(
        identifier=_required_string_field(response, "identifier", context),
        proof_type="uniqueness",
        signal_hash=_optional_string_field(response, "signal_hash", context),
        nullifier=_required_string_field(response, "nullifier", context),
        issuer_schema_id=_positive_int_field(response, "issuer_schema_id", context),
        expires_at_min=_positive_int_field(response, "expires_at_min", context),
    )


def _normalize_v4_session_response(response: Mapping[str, Any], index: int) -> WorldIdCredentialResponse:
    context = f"IDKit response responses[{index}]"
    if "nullifier" in response:
        raise WorldIdPayloadError(f"{context} must not include nullifier for session proofs")
    _proof_list(response, context)
    session_nullifier = response.get("session_nullifier")
    if not isinstance(session_nullifier, list) or len(session_nullifier) != 2:
        raise WorldIdPayloadError(f"{context}.session_nullifier must be a two-item list")
    session_values = [
        _non_empty_string(value, f"{context}.session_nullifier[{index}]")
        for index, value in enumerate(session_nullifier)
    ]
    return WorldIdCredentialResponse(
        identifier=_required_string_field(response, "identifier", context),
        proof_type="session",
        signal_hash=_optional_string_field(response, "signal_hash", context),
        session_nullifier=session_values[0],
        session_action=session_values[1],
        issuer_schema_id=_positive_int_field(response, "issuer_schema_id", context),
        expires_at_min=_positive_int_field(response, "expires_at_min", context),
    )


def _response_items(payload: Mapping[str, Any]) -> list[Mapping[str, Any]]:
    raw_responses = payload.get("responses")
    if not isinstance(raw_responses, list) or not raw_responses:
        raise WorldIdPayloadError("IDKit response responses must be a non-empty list")
    responses: list[Mapping[str, Any]] = []
    for index, response in enumerate(raw_responses):
        if not isinstance(response, Mapping):
            raise WorldIdPayloadError(f"IDKit response responses[{index}] must be a JSON object")
        responses.append(response)
    return responses


def _proof_list(response: Mapping[str, Any], context: str) -> list[str]:
    proof = response.get("proof")
    if not isinstance(proof, list) or len(proof) < 5:
        raise WorldIdPayloadError(f"{context}.proof must be a list with at least five proof elements")
    return [_non_empty_string(value, f"{context}.proof[{index}]") for index, value in enumerate(proof)]


def _required_string_field(source: Mapping[str, Any], name: str, context: str) -> str:
    if name not in source:
        raise WorldIdPayloadError(f"{context}.{name} is required")
    return _non_empty_string(source.get(name), f"{context}.{name}")


def _optional_string_field(source: Mapping[str, Any], name: str, context: str) -> str:
    if name not in source or source.get(name) is None:
        return ""
    return _non_empty_string(source.get(name), f"{context}.{name}")


def _non_empty_string(value: Any, context: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise WorldIdPayloadError(f"{context} must be a non-empty string")
    return value.strip()


def _optional_bool_field(source: Mapping[str, Any], name: str, context: str) -> bool | None:
    if name not in source or source.get(name) is None:
        return None
    value = source.get(name)
    if not isinstance(value, bool):
        raise WorldIdPayloadError(f"{context}.{name} must be a boolean")
    return value


def _positive_int_field(source: Mapping[str, Any], name: str, context: str) -> int:
    if name not in source:
        raise WorldIdPayloadError(f"{context}.{name} is required")
    value = source.get(name)
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise WorldIdPayloadError(f"{context}.{name} must be a positive integer")
    return value


def _integrity_bundle_present(payload: Mapping[str, Any]) -> bool:
    if "integrity_bundle" not in payload or payload.get("integrity_bundle") is None:
        return False
    if not isinstance(payload.get("integrity_bundle"), Mapping):
        raise WorldIdPayloadError("IDKit response integrity_bundle must be a JSON object")
    return True


def _validate_enabled_config(config: WorldIdConfig) -> None:
    missing: list[str] = []
    if not config.app_id:
        missing.append("WORLD_ID_APP_ID")
    if not config.rp_id:
        missing.append("WORLD_ID_RP_ID")
    if not config.rp_signing_key.configured:
        missing.append("WORLD_ID_RP_SIGNING_KEY or WORLD_ID_RP_SIGNING_KEY_SECRET_REF")
    if not config.nullifier_hmac_key.configured:
        missing.append("WORLD_ID_NULLIFIER_HMAC_KEY or WORLD_ID_NULLIFIER_HMAC_KEY_SECRET_REF")
    if missing:
        raise WorldIdConfigError(f"World ID is enabled but missing required configuration: {', '.join(missing)}")
    if not config.app_id.startswith("app_"):
        raise WorldIdConfigError("WORLD_ID_APP_ID must start with app_")
    if not config.rp_id.startswith("rp_"):
        raise WorldIdConfigError("WORLD_ID_RP_ID must start with rp_")


def _actions_from_env(env: Mapping[str, str] | None, default_action: str) -> list[str]:
    raw = _str_env(env, "WORLD_ID_ALLOWED_ACTIONS", default_action)
    actions = []
    for item in raw.split(","):
        action = item.strip()
        if not action:
            continue
        if any(char.isspace() for char in action):
            raise WorldIdConfigError("World ID actions must not contain whitespace")
        if action not in actions:
            actions.append(action)
    if not actions:
        raise WorldIdConfigError("At least one World ID action must be configured")
    return actions


def _reject_public_secret_leaks(env: Mapping[str, str] | None) -> None:
    source = env if env is not None else os.environ
    leaked = sorted(name for name in _PUBLIC_SECRET_ENV_NAMES if str(source.get(name) or "").strip())
    if leaked:
        raise WorldIdConfigError(
            "World ID signing/nullifier secrets must not be configured in browser-exposed env vars: "
            + ", ".join(leaked)
        )


def _str_env(env: Mapping[str, str] | None, name: str, default: str) -> str:
    source = env if env is not None else os.environ
    return str(source.get(name) or default).strip()


def _secret_env(env: Mapping[str, str] | None, name: str) -> str:
    if env is not None:
        return str(env.get(name) or "").strip()
    return resolve_secret(name).strip()


def _bool_env(env: Mapping[str, str] | None, name: str, *, default: bool) -> bool:
    raw = _str_env(env, name, "")
    if not raw:
        return default
    lowered = raw.lower()
    if lowered in {"1", "true", "yes", "on", "enabled"}:
        return True
    if lowered in {"0", "false", "no", "off", "disabled"}:
        return False
    raise WorldIdConfigError(f"{name} must be a boolean value")


def _positive_int_env(env: Mapping[str, str] | None, name: str, default: int) -> int:
    raw = _str_env(env, name, str(default))
    try:
        value = int(raw)
    except ValueError as exc:
        raise WorldIdConfigError(f"{name} must be an integer") from exc
    if value <= 0:
        raise WorldIdConfigError(f"{name} must be positive")
    return value


def _positive_float_env(env: Mapping[str, str] | None, name: str, default: float) -> float:
    raw = _str_env(env, name, str(default))
    try:
        value = float(raw)
    except ValueError as exc:
        raise WorldIdConfigError(f"{name} must be a number") from exc
    if value <= 0:
        raise WorldIdConfigError(f"{name} must be positive")
    return value


def _url_env(env: Mapping[str, str] | None, name: str, default: str) -> str:
    try:
        return _validate_base_url(_str_env(env, name, default))
    except WorldIdVerificationError as exc:
        raise WorldIdConfigError(f"{name} must be an absolute http(s) URL") from exc


def _require_signing_dependencies() -> None:
    if _SIGNING_IMPORT_ERROR is not None:
        raise WorldIdSignatureError("World ID signing dependencies are not installed") from _SIGNING_IMPORT_ERROR


def _require_keccak_dependency() -> None:
    if _KECCAK_IMPORT_ERROR is not None:
        raise WorldIdSignatureError("World ID Keccak dependency is not installed") from _KECCAK_IMPORT_ERROR


def _parse_private_key(value: str) -> bytes:
    raw = str(value or "").strip()
    if raw.startswith("0x"):
        raw = raw[2:]
    try:
        key = bytes.fromhex(raw)
    except ValueError as exc:
        raise WorldIdSignatureError("signing key must be 32 bytes of hex") from exc
    if len(key) != 32:
        raise WorldIdSignatureError("signing key must be 32 bytes")
    return key


def _parse_bytes32(value: bytes | str, name: str) -> bytes:
    if isinstance(value, str):
        raw = value.strip()
        if raw.startswith("0x"):
            raw = raw[2:]
        try:
            data = bytes.fromhex(raw)
        except ValueError as exc:
            raise WorldIdSignatureError(f"{name} must be 32 bytes of hex") from exc
    else:
        data = bytes(value)
    if len(data) != 32:
        raise WorldIdSignatureError(f"{name} must be exactly 32 bytes")
    return data


def _uint64(value: int, name: str) -> int:
    parsed = int(value)
    if parsed < 0 or parsed > 2**64 - 1:
        raise WorldIdSignatureError(f"{name} must fit uint64")
    return parsed


def _validate_base_url(value: str) -> str:
    normalized = str(value or "").strip().rstrip("/")
    parsed = urlparse(normalized)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise WorldIdVerificationError("base URL must be an absolute http(s) URL")
    return normalized


def _default_world_id_request_json(
    method: str,
    url: str,
    payload: Mapping[str, Any],
    headers: Mapping[str, str],
    timeout_seconds: float,
) -> Mapping[str, Any]:
    request_body = json.dumps(payload).encode("utf-8")
    req = urllib_request.Request(
        url,
        data=request_body,
        headers=dict(headers),
        method=method,
    )
    try:
        with urllib_request.urlopen(req, timeout=timeout_seconds) as response:
            raw = response.read().decode("utf-8")
    except urllib_error.HTTPError as exc:
        raw_error = exc.read().decode("utf-8", errors="replace")
        raise WorldIdVerificationError(
            f"World ID verification request failed with status {exc.code}: {_redact_text(raw_error)}"
        ) from exc
    try:
        parsed = json.loads(raw or "{}")
    except Exception as exc:
        raise WorldIdVerificationError("World ID verification response was not valid JSON") from exc
    if not isinstance(parsed, Mapping):
        raise WorldIdVerificationError("World ID verification response must be a JSON object")
    return parsed


def _safe_error_message(exc: Exception) -> str:
    return _redact_text(str(exc))


def _redact_text(value: str, *, limit: int = 500) -> str:
    text = str(value or "")
    for marker in ("proof", "nullifier", "session_nullifier", "merkle_root", "signal_hash", "jwt"):
        if marker in text.lower():
            return "[redacted World ID verification error]"
    return text[:limit]
